---
freebsd_base_ntp_servers:
  - "0.freebsd.pool.ntp.org"
  - "1.freebsd.pool.ntp.org"
  - "2.freebsd.pool.ntp.org"

freebsd_base_syslog_remote_target: "{{ hostvars['hetzner-3'].ansible_facts.tailscale0.ipv4.address }}"
freebsd_base_syslog_remote_port: "1514"

freebsd_base_pkg_update_day: "6"
freebsd_base_pkg_update_hour: "22"

freebsd_base_ext_if: "ena0"
