trusted {
  priority = high;
  local = yes;
  want_spam = yes;
}

authenticated {
  priority = high;
  authenticated = yes;
  apply {
    groups_disabled = ["rbl", "spf"];
    symbols_disabled = ["BAYES_SPAM", "NEURAL_SPAM", "PHISHING"];
    actions {
      reject = null;
    }
  }
}

public_aliases {
  priority = high;
  rcpt = "info@gnome.org";
  rcpt = "accounting@gnome.org";
  rcpt = "zana@gnome.org";
  apply {
    BAYES_SPAM = 6.0;
    GPT_HAM = -0.5;
    GPT_MARKETING = 1.0;
  }
}
