#!/usr/bin/python3

import datetime
import socket
import time

import OpenSSL


def main():
    shortname = socket.gethostname().split('.')[0]
    certfile = "/etc/openvpn/keys/non-phx2-machines-{}.crt".format(shortname)

    with open(certfile, "r") as f:
        cert = f.read()

    x509 = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, cert)
    not_after = x509.get_notAfter()[0:8].decode("UTF-8")
    not_after_dt = datetime.datetime.strptime(not_after, "%Y%m%d").timetuple()
    timestamp = time.mktime(not_after_dt)

    output = [
      "# HELP openvpn_cert_not_after Returns OpenVPN certificate expiry date in unixtime",
      "# TYPE openvpn_cert_not_after gauge",
      "openvpn_cert_not_after {}".format(int(timestamp)),
      ""
    ]

    with open("/var/lib/node_exporter/openvpn_cert_not_after.prom", "w") as f:
        f.write("\n".join(output))


if __name__ == "__main__":
    main()
